name: Build and Deploy

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64, x86]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ensure clang installed
        run: clang++ --version

      - name: ensure make installed
        run: make --version

      - name: Setup
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCI=ON -DCMAKE_GENERATOR_PLATFORM=$({{ matrix.arch }})

      - name: Build
        run: cmake --build build

      - name: Test
        run: cd build/tests && ctest

      - name: Upload Artefacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}-${{ matrix.arch }}
          path: build

  release:
    runs-on: windows-latest
    if: success() || failure()
    needs: [build-and-test]
    steps:
      - name: Download packages for Windows x64
        uses: actions/download-artifact@v2
        with:
          name: build-windows-latest-x64
      - name: Download packages for Windows x86
        uses: actions/download-artifact@v2
        with:
          name: build-windows-latest-x86
      - name: Download packages for Linux x64
        uses: actions/download-artifact@v2
        with:
          name: build-ubuntu-latest-x64
      - uses: softprops/action-gh-release@v1
        with:
          files: |
           './build-windows-latest-x64/**' 
           './build-windows-latest-x86/**'
           './build-ubuntu-latest-x64/**'
          token: ${{ secrets.SUPER_SECRET_TOKEN }}